//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxiomIRISRibbon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowAllLogins {
            get {
                return ((bool)(this["ShowAllLogins"]));
            }
            set {
                this["ShowAllLogins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dev-CS--IRIS----RKSB1-CS17-my-salesforce-com.iris-dev.rowini.net:29443")]
        public string DevUrl {
            get {
                return ((string)(this["DevUrl"]));
            }
            set {
                this["DevUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00Dg0000003Nc8C")]
        public string DevOrgId {
            get {
                return ((string)(this["DevOrgId"]));
            }
            set {
                this["DevOrgId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Debug {
            get {
                return ((bool)(this["Debug"]));
            }
            set {
                this["Debug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Prod")]
        public string Inst {
            get {
                return ((string)(this["Inst"]));
            }
            set {
                this["Inst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://it-CS--IRIS----QA1SB-CS17-my-salesforce-com.iris-it.rowini.net:29443")]
        public string ITUrl {
            get {
                return ((string)(this["ITUrl"]));
            }
            set {
                this["ITUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00Dg0000003NdAc")]
        public string ITOrgId {
            get {
                return ((string)(this["ITOrgId"]));
            }
            set {
                this["ITOrgId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://uat-cs--iris----csuat-cs17-my-salesforce-com.iris-uat.csintra.net")]
        public string UATUrl {
            get {
                return ((string)(this["UATUrl"]));
            }
            set {
                this["UATUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00Dg0000003Nc8e")]
        public string UATOrgId {
            get {
                return ((string)(this["UATOrgId"]));
            }
            set {
                this["UATOrgId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://prod-cs--iris-my-salesforce-com.iris.csintra.net")]
        public string ProdUrl {
            get {
                return ((string)(this["ProdUrl"]));
            }
            set {
                this["ProdUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00Dj0000000Hojv")]
        public string ProdOrgId {
            get {
                return ((string)(this["ProdOrgId"]));
            }
            set {
                this["ProdOrgId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29.0")]
        public string SoapVersion {
            get {
                return ((string)(this["SoapVersion"]));
            }
            set {
                this["SoapVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SSOLogin {
            get {
                return ((bool)(this["SSOLogin"]));
            }
            set {
                this["SSOLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Windows8")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#003565")]
        public string ThemeColor {
            get {
                return ((string)(this["ThemeColor"]));
            }
            set {
                this["ThemeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://CHWD2500274.ch.ad.hedani.net:29080/irisreports/SSOLogin.aspx")]
        public string ReportsDevUrl {
            get {
                return ((string)(this["ReportsDevUrl"]));
            }
            set {
                this["ReportsDevUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://CHWT2500276.ch.ad.hedani.net:29080/irisreports/SSOLogin.aspx")]
        public string ReportsITUrl {
            get {
                return ((string)(this["ReportsITUrl"]));
            }
            set {
                this["ReportsITUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://iris-an-uat.csintra.net/IRISReports/SSOLogin.aspx")]
        public string ReportsUATUrl {
            get {
                return ((string)(this["ReportsUATUrl"]));
            }
            set {
                this["ReportsUATUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://iris-an.csintra.net/IRISReports/SSOLogin.aspx")]
        public string ReportsProdUrl {
            get {
                return ((string)(this["ReportsProdUrl"]));
            }
            set {
                this["ReportsProdUrl"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cs17.salesforce.com/services/Soap/class/Axiom_RibbonController")]
        public string AxiomIRISRibbon_sfRibbon_Axiom_RibbonControllerService {
            get {
                return ((string)(this["AxiomIRISRibbon_sfRibbon_Axiom_RibbonControllerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://login.salesforce.com/services/Soap/u/31.0")]
        public string AxiomIRISRibbon_sfPartner_SforceService {
            get {
                return ((string)(this["AxiomIRISRibbon_sfPartner_SforceService"]));
            }
        }
    }
}
